"""Semantic relationship keys."""

# single-target
LOCATED_IN = "LOCATED_IN"
HAS_JOB = "HAS_JOB"
OWNS_RADIO = "OWNS_RADIO"
SIDE_A = "SIDE_A"
SIDE_B = "SIDE_B"
SUBJECT = "SUBJECT"
SOURCE = "SOURCE"
DERIVED_FROM = "DERIVED_FROM"
PERFORMED_BY = "PERFORMED_BY"

# many-target
BELIEVES = "BELIEVES"
TARGETS = "TARGETS"
